- package.json
- tests/Comments/__snapshots__/jsfmt.spec.js.snap
- tests/ConstantValue/__snapshots__/jsfmt.spec.js.snap
- tests/ControlStructures/__snapshots__/jsfmt.spec.js.snap
- tests/Declaration/__snapshots__/jsfmt.spec.js.snap
- tests/Element/__snapshots__/jsfmt.spec.js.snap
- tests/Expressions/__snapshots__/jsfmt.spec.js.snap
- tests/Failing/__snapshots__/jsfmt.spec.js.snap
- tests/GenericTagCustomPrint/__snapshots__/jsfmt.spec.js.snap
- tests/GenericTags/__snapshots__/jsfmt.spec.js.snap
- tests/IncludeEmbed/__snapshots__/jsfmt.spec.js.snap
- tests/Options/__snapshots__/jsfmt.spec.js.snap
- tests/PrettierIgnore/__snapshots__/jsfmt.spec.js.snap
- tests/Statements/__snapshots__/jsfmt.spec.js.snap
- tests/TwigCodingStandards/__snapshots__/jsfmt.spec.js.snap
- tests/Whitespace/__snapshots__/jsfmt.spec.js.snap
- yarn.lock
Only `eslint-plugin-prettier` is kept on version 4 because we haven't fixed compatibility with prettier 3.
Update test snapshots.
> Chore: Bump dev dependencies to latest version

- package.json
- yarn.lock
Prettier 3 support has been added to jest version 30. Unfortunately it hasn't been released yet.
> Chore: Upgrade jest to pre-release version 30

- .eslintrc.yml
- package.json
- tests/switch-plugin/index.js
- yarn.lock
`concat` function has been deprecated since prettier 2.3.0.
> Lint: Make sure that `prettier-doc/no-concat` is enforced

- CHANGELOG.md
- package.json
Ref: https://stackoverflow.com/a/72176325/6265296
When publishing to npm, the existence of npm script named 'publish' will trigger publishing packages twice for the same version.
> Chore: Remove npm script to publish

- CHANGELOG.md
- README.md
- package.json
The npm package has been renamed from `@zackad/prettier-plugin-twig-melody` into `@zackad/prettier-plugin-twig` to clearly indicate that this project is focusing only on formating twig template.
> Meta: Rename package

- package.json
- src/index.js
- tests/Comments/__snapshots__/jsfmt.spec.js.snap
- tests/Comments/jsfmt.spec.js
- tests/ConstantValue/__snapshots__/jsfmt.spec.js.snap
- tests/ConstantValue/jsfmt.spec.js
- tests/ControlStructures/__snapshots__/jsfmt.spec.js.snap
- tests/ControlStructures/jsfmt.spec.js
- tests/Declaration/__snapshots__/jsfmt.spec.js.snap
- tests/Declaration/jsfmt.spec.js
- tests/Element/__snapshots__/jsfmt.spec.js.snap
- tests/Element/jsfmt.spec.js
- tests/Expressions/__snapshots__/jsfmt.spec.js.snap
- tests/Expressions/jsfmt.spec.js
- tests/Failing/__snapshots__/jsfmt.spec.js.snap
- tests/Failing/jsfmt.spec.js
- tests/GenericTags/__snapshots__/jsfmt.spec.js.snap
- tests/GenericTags/jsfmt.spec.js
- tests/IncludeEmbed/__snapshots__/jsfmt.spec.js.snap
- tests/IncludeEmbed/jsfmt.spec.js
- tests/Options/__snapshots__/jsfmt.spec.js.snap
- tests/Options/jsfmt.spec.js
- tests/PrettierIgnore/__snapshots__/jsfmt.spec.js.snap
- tests/PrettierIgnore/jsfmt.spec.js
- tests/Statements/__snapshots__/jsfmt.spec.js.snap
- tests/Statements/jsfmt.spec.js
- tests/TwigCodingStandards/__snapshots__/jsfmt.spec.js.snap
- tests/TwigCodingStandards/jsfmt.spec.js
- tests/Whitespace/__snapshots__/jsfmt.spec.js.snap
- tests/Whitespace/jsfmt.spec.js
Close GH-36
Hopefully this will be the last BREAKING CHANGE before version 1 release.
> Rename parser/AST from 'melody' into 'twig'

- CHANGELOG.md
- src/melody/melody-parser/CharStream.js
- src/melody/melody-parser/Lexer.js
- tests/Element/__snapshots__/jsfmt.spec.js.snap
- tests/Element/alpinejs.twig
> support attribute names according to html5 specs

- CHANGELOG.md
- vitest.config.js
If you use nix flakes and enabling it using direnv, there will be `.devenv` and `.direnv` directories in your root project directory. By default vitest will try to look for test files in all directories unless it is being excluded. Unfortunately `.devenv` and `.direnv` is not on that list.
All we need is just tell vitest only to look for in `tests` directory.
> Optimize test files lookup

- CHANGELOG.md
- package.json
I don't see the value of having this npm script alias. Having this script alias make it difficult to format our codebase. Instead of `yarn prettier --write filename.js` we need to run
`./node_modules/.bin/prettier --write filename.js` which more verbose.
> Remove npm script alias to run prettier

- .eslintrc.yml
- CHANGELOG.md
- src/melody/melody-parser/Lexer.js
- src/melody/melody-parser/Parser.js
- src/melody/melody-parser/TokenTypes.js
- src/melody/melody-types/index.js
- src/print/ArrowFunction.js
- src/printer.js
- tests/Expressions/__snapshots__/jsfmt.spec.js.snap
- tests/Expressions/arrowFunctions.twig
Adds support for arrow functions inside filters, which makes formatting `|filter()`, `|map()` and `|reduce()` filters possible, resolving  #19.
Includes a new test file for three scenarios:
* Arrow function with one argument: 
```twig
{{ someArray|filter(item => item.amount > 5) }}
```
* Arrow function with multiple arguments:
```twig
{{ someArray|map((value, key) => "key #{key} with value #{value}") }}
```
* Arrow function with multiple arguments and second filter argument:
```twig
{{ numbers|reduce((carry, v, k) => carry + v * k, 10) }}
```
I also tested with a variety of other combinations, including named parameters, which all seem to work. I will post my notes in the corresponding issue, in case someone is interested.
> Add support for arrow functions

- CHANGELOG.md
- src/melody/melody-extension-core/operators.js
- tests/Expressions/__snapshots__/arrowFunctions.snap.twig
- tests/Expressions/__snapshots__/operators.snap.twig
- tests/Expressions/arrowFunctions.twig
- tests/Expressions/operators.twig
> Feature: Add support for three-way-comparison (spaceship) operator

- CHANGELOG.md
- src/melody/melody-parser/Parser.js
- src/melody/melody-types/index.js
- src/print/ObjectProperty.js
Close GH-58.
```twig
{# keys can be omitted if it is the same as the variable name #}
{foo}
{# is equivalent to the following #}
{'foo': foo}
```
Ref: https://twig.symfony.com/doc/3.x/templates.html#literals
> Refactor: Make `key` on `ObjectProperty` type optional

- CHANGELOG.md
- src/print/AutoescapeBlock.js
- tests/Statements/__snapshots__/autoescape.snap.twig
- tests/Statements/autoescape.twig
Close GH-63
Ref:
- https://twig.symfony.com/doc/3.x/tags/autoescape.html
> Bugfix: Allow boolean value as autoescape type

- CHANGELOG.md
- src/melody/melody-extension-core/visitors/filters.js
- src/print/AutoescapeBlock.js
Close GH-66
This patch also contains fix to use template function from `@babel/template` that for some reason behave differently between test environment and loading directly on prettier cli.
> Bugfix: lodash named import is not supported

- CHANGELOG.md
- src/melody/melody-extension-core/parser/macro.js
- src/melody/melody-types/index.js
- src/print/Identifier.js
- tests/Statements/__snapshots__/macro.snap.twig
- tests/Statements/macro.twig
> Feature: Add support for default argument value of macros

- CHANGELOG.md
- src/melody/melody-parser/Parser.js
- tests/Expressions/__snapshots__/callExpression.snap.twig
- tests/Expressions/callExpression.twig
Close GH-74
Ref: https://twig.symfony.com/doc/3.x/templates.html#named-arguments
> Feature: Support for colon as separators between argument names and values

- CHANGELOG.md
- src/print/NamedArgumentExpression.js
- tests/Expressions/__snapshots__/callExpression.snap.twig
- tests/TwigCodingStandards/__snapshots__/disable_twig_coding_standards.snap.twig
- tests/TwigCodingStandards/__snapshots__/enable_twig_coding_standards.snap.twig
- tests/TwigCodingStandards/disable_twig_coding_standards.twig
- tests/TwigCodingStandards/enable_twig_coding_standards.twig
- tests/TwigCodingStandards/jsfmt.spec.js
- tests/smoke-test.twig
Close GH-71
BREAKING CHANGES:
- Make sure to update twig to version 3.12 or later
- Separator between argument names and values has been changed from ` = ` into `: ` for named arguments
> Feature: Update twig coding standards to follow version 3.x

- CHANGELOG.md
- src/melody/melody-extension-core/parser/macro.js
- tests/Statements/__snapshots__/macro.snap.twig
- tests/Statements/macro.twig
> Bugfix: Handle empty string as default value on macro declaration

- CHANGELOG.md
- README.md
- src/index.js
- src/printer.js
- tests/Failing/jsfmt.spec.js
- tests/Options/jsfmt.spec.js
Related GH-50.
- Option `twigPrintWidth` has been removed
I don't see any reason why we should keep the option `twigPrintWidth`. Prettier provide mechanism to use different `printWidth` for different file types by using _override_ (see example below).
__What to do?__
Remove `twigPrintWidth` from your prettier config and use [override](https://prettier.io/docs/en/configuration.html#configuration-overrides) instead.
__Example__
```diff
- twigPrintWidth: 120
+ overrides:
+   - files: "*.twig"
+     options:
+       printWidth: 120
```
> Feature: Remove option `twigPrintWidth`

- CHANGELOG.md
- src/melody/melody-extension-core/operators.js
- src/melody/melody-parser/Parser.js
- src/print/UnarySubclass.js
- tests/Expressions/__snapshots__/spread_operator.snap.twig
- tests/Expressions/jsfmt.spec.js
- tests/Expressions/spread_operator.twig
Close GH-44.
Partially depends on GH-16.
Need help on how to parse this expression
```shell
Error: Error: ERROR: Invalid map key
32 | <twig:Component {{ ...vars }} />
33 | {% set numbers = [1, 2, ...moreNumbers] %}
> 34 | {% set ratings = {'foo': 10, 'bar': 5, ...moreRatings} %}
|                                        ^
35 | 
```
> Feature: Add support for spread operator

- package.json
This will allow downstream package to access this plugin metadata.
> Chore: Add package.json as exports

- CHANGELOG.md
- src/print/Element.js
- tests/ControlStructures/__snapshots__/forInclude.snap.twig
- tests/ControlStructures/__snapshots__/if.snap.twig
- tests/Element/__snapshots__/attributes.snap.twig
- tests/Element/__snapshots__/manyAttributes.snap.twig
- tests/Element/__snapshots__/selfClosing.snap.twig
- tests/Expressions/__snapshots__/mappingExpression.snap.twig
- tests/Expressions/__snapshots__/objectExpression.snap.twig
- tests/Failing/__snapshots__/controversial.snap.twig
- tests/Failing/__snapshots__/failing.snap.twig
- tests/Statements/__snapshots__/macro.snap.twig
- tests/smoke-test.twig
This is how prettier handle multiline html attribute.
__Input__
```twig
<iframe class=""
src="https://www.google.com/maps/embed"
frameborder="0"
allowfullscreen></iframe>
```
__Output__
```diff
- <iframe class=""
+ <iframe
+     class=""
src="https://www.google.com/maps/embed"
frameborder="0"
allowfullscreen></iframe>
```
- [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAlgMwE4EMC2cABGADa4DOFAvADoj21REussXZh0gAWMMABwpIA9CIDukgHQBzCBBmk4UyPhH5cQkXHwAjOABNGzNqxwE4uiNgNxs3AAzHTrXKVIRxmAK7uKYbDgEAD5UESw8QmCmJgx8GSIeQMxuPkFhMQFA-nQ7KXQIEQFyAE8ZbAhvKAMAam8AQXqAWQB1CgBxKAAWAGVxAV0ASRlBxoA3CgB5GXr6IjcYbgoIQiJbf2x0ARgCqDmRYJAAGhAIbd2KZFBcbArxAAUbhEuUN3FcEsuT3TwwAGs4DAehYADLoKBwZCYNwUODfX4AoECXBgcEyZAwbDeOEgWH4dAYrE4uAADwEdnQhFgbgAKnYoDdci9oaRYScKGilABFbwQeBQmE4gBWFBJPU5cB5fMhSBZbJ …
> Bugfix: Fix html attribute indentation when printed on multiline

- CHANGELOG.md
- tests_config/run_spec.js
With this feature we can use single input to generate several ouput snapshot for different configuration.
> Test: Add option to add prefix and/or suffix to test output

- CHANGELOG.md
- src/print/BlockStatement.js
- tests/IncludeEmbed/__snapshots__/block_shortcut.snap.twig
- tests/IncludeEmbed/block_shortcut.twig
- tests/IncludeEmbed/jsfmt.spec.js
> Bugfix: Handle string literal body when using block shortcut syntax

- CHANGELOG.md
- src/print/Element.js
- src/util/publicFunctions.js
- tests/ControlStructures/__snapshots__/forWithBlock.snap.twig
- tests/Element/__snapshots__/ownline_html_element.snap.twig
- tests/Element/jsfmt.spec.js
- tests/Element/ownline_html_element.twig
- tests/Expressions/__snapshots__/operators.snap.twig
- tests/smoke-test.twig
Close GH-101
This html tags will be printed on their own line:
- h1
- h2
- h3
- h4
- h5
- h6
- li
- td
- th
> Bugfix: Print some html element as their own line

- CHANGELOG.md
- tests_config/run_spec.js
Inspecting ast object using debugger is hard, especially when ast contains a lot of nested children.
__Example ast with nested children__
There's a lot noise that might not relevant when inspecting ast structure.
__Example of strigified ast object__
IMO, stringified ast is easier to inspect.
> Test: Stringify ast object on test setup

- CHANGELOG.md
- src/melody/melody-parser/Parser.js
- tests/Element/__snapshots__/attribute_twig_comment.snap.twig
- tests/Element/attribute_twig_comment.twig
- tests/Element/jsfmt.spec.js
Partially implement GH-61
This will allow twig comment inside html element as attribute.
__Example__
```twig
<button
type="button"
{# Some comment here #}
class="flex-shrink-0 size-6 grid place-items-center"
>
Foo
</button>
```
> [!NOTE]
> Do not put comment as attribute value
__Invalid__
```twig
<button
type="button"
comment="{# Some comment here #}"
class="flex-shrink-0 size-6 grid place-items-center"
>
Foo
</button>
```
> Feature: Add support for twig comment as html element attribute

- CHANGELOG.md
- src/print/EmbedStatement.js
- tests/Failing/__snapshots__/failing.snap.twig
- tests/Failing/failing.twig
- tests/IncludeEmbed/__snapshots__/embed.snap.twig
- tests/IncludeEmbed/embed.twig
PR suggested in the trivago repository: https://github.com/trivago/prettier-plugin-twig-melody/pull/59
> Bugfix: Support "only" modifier in embed statements

- CHANGELOG.md
- README.md
- src/index.js
- src/melody/melody-extension-core/operators.js
- src/parser.js
- src/print/TestExpression.js
- tests/Expressions/__snapshots__/custom_test_expression.snap.twig
- tests/Expressions/custom_test_expression.twig
- tests/Expressions/jsfmt.spec.js
This PR adds the new config option `twigTestExpressions`, which allows the user to register any custom Twig tests. This makes those custom tests known to the parser without throwing any errors.
@zackad I tried to add the functionality with the best of my knowledge on how to integrate something like that in a Prettier plugin, like this one. I hope we can work with that and I'm always very grateful for inputs. Let me know, if I can do something differently to refactor this implementation.
> Feature: Allow registering custom Twig tests expression
